Add set_weights and get_weighst APIs
SciSharp/TensorFlow.NET pull request #1030
Opened 2023-04-20 02:52 UTC by Wanglongzhi2001

finish #1025

2023-04-20 03:25 UTC, Wanglongzhi2001 commented
The following give a simple example of usage:
```
var layers = keras.layers;

            // input layer
            var inputs = keras.Input(shape: (10), name: "img");
            // convolutional layer
            var x = layers.Dense(10).Apply(inputs);
            // output layer
            var outputs = layers.Dense(20).Apply(x);
            // build keras model
            var model = keras.Model(inputs, outputs, name: "test_weights_api");
            model.summary();
            // compile keras model in tensorflow static graph
            model.compile(optimizer: keras.optimizers.Adam(),
                loss: keras.losses.SparseCategoricalCrossentropy(from_logits: true),
                metrics: new[] { "acc" });

            // get weights which return a list of NDArray
            var ini_weights = model.get_weights();
            foreach (var item in model.get_weights())
            {
                Console.WriteLine($"before: {item}");
            }

            // change weights and set_weights which needs to pass a List of NDArray
            for (int i = 0; i < len(ini_weights); i++)
            {
                ini_weights[i] *= 0.2;
            }
            model.set_weights(ini_weights);
            foreach (var item in model.get_weights())
            {
                Console.WriteLine($"after: {item}");
            }
```
results:
```
 DropoutTest
   源: MyTest.cs 行 16
   持续时间: 205 毫秒

  标准输出: 
Model: test_weights_api 
_________________________________________________________________ 
Layer (type)                  Output Shape              Param #   
================================================================= 
img (InputLayer)              (None, 10)                0         
_________________________________________________________________ 
dense (Dense)                 (None, 10)                110       
_________________________________________________________________ 
dense_1 (Dense)               (None, 20)                220       
================================================================= 
Total params: 330 
Trainable params: 330 
Non-trainable params: 0 
_________________________________________________________________ 
before: array([[0.4290732, 0.43938243, -0.10135594, -0.53019816, -0.33572856, -0.17829558, -0.34261298, -0.34164312, -0.23591474, -0.43701828], 
[-0.19869763, -0.1563918, 0.46223533, 0.456756, -0.0719178, 0.31607074, 0.26863712, -0.2638809, 0.06243509, 0.17580843], 
[0.43452996, 0.28923744, -0.24953079, 0.23461801, -0.47469088, 0.19796163, -0.340703, -0.05029151, 0.01263994, 0.2523926], 
[-0.19152328, -0.20255569, 0.16217262, 0.44851583, -0.53923386, 0.25585616, 0.504377, 0.092785895, 0.19725674, 0.46969593], 
[-0.47458458, -0.45688558, 0.32023972, 0.33621907, -0.053389817, 0.24259675, -0.08634299, 0.4331708, -0.40340513, -0.09086874], 
[0.13816285, -0.49154812, 0.15877634, -0.2509495, 0.12785232, 0.33574253, 0.5291879, 0.11309129, 0.49851632, -0.1880289], 
[0.26949954, -0.0036470294, -0.19133577, 0.25588882, 0.13915008, -0.24662432, -0.4698529, 0.09722352, 0.19060189, 0.5091355], 
[-0.3024518, -0.40109205, 0.04155141, 0.076616585, -0.21239245, -0.17724162, -0.33276385, -0.27774572, -0.42425314, -0.34030056], 
[0.0033610463, -0.2211811, -0.3657294, 0.08356446, 0.2034638, 0.5185646, -0.5080707, 0.29126936, 0.31920576, 0.38711464], 
[0.24035746, 0.5319679, -0.41026175, 0.44290292, 0.08448082, 0.004024327, 0.08626908, 0.39570755, -0.3957219, -0.19006279]])
before: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
before: array([[-0.26928133, -0.062072456, -0.1694741, -0.16391802, -0.18297634, ..., 0.10726899, -0.43808722, 0.09421277, -0.14846385, 0.3876887], 
[-0.21272261, -0.36469075, 0.30485535, 0.208246, -0.18951353, ..., 0.3041464, 0.4388559, -0.4214669, -0.40380344, -0.3385527], 
[-0.44229203, 0.14724344, 0.31642824, -0.17053565, -0.18032297, ..., 0.13653588, -0.10565406, -0.17600003, -0.2859696, -0.20755242], 
[-0.09491086, 0.42670488, -0.28042054, -0.17883855, 0.0890829, ..., -0.05500862, 0.18488806, 0.023785144, -0.0060749054, -0.41644946], 
[0.34600598, 0.064317405, -0.24650826, 0.28952187, -0.16855168, ..., 0.39845997, 0.35254383, -0.1273947, 0.2035814, 0.3774643], 
[-0.11834085, -0.17418623, 0.33386266, -0.15681922, 0.41952235, ..., 0.236301, 0.0049164295, -0.18161464, -0.104362756, 0.1350115], 
[-0.32884598, -0.121868074, -0.23042189, -0.22418556, 0.28875154, ..., 0.06157452, 0.24738908, 0.0036130548, 0.36984122, -0.1413421], 
[0.24626923, -0.1665962, -0.13581085, -0.114598006, -0.43259266, ..., -0.27370527, -0.11548874, -0.21051784, -0.36405462, -0.20202492], 
[-0.13987389, -0.32427, 0.05172077, -0.3697783, -0.20936672, ..., -0.101902604, -0.29761082, -0.14468816, 0.17017198, -0.4032636], 
[-0.272566, 0.16334343, 0.17212158, 0.42669892, 0.41524398, ..., -0.042738855, 0.2598809, -0.39048365, 0.24863678, 0.19401616]])
before: array([0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0])
after: array([[0.08581465, 0.08787649, -0.020271188, -0.106039636, -0.06714571, -0.035659116, -0.068522595, -0.06832863, -0.047182947, -0.087403655], 
[-0.039739527, -0.03127836, 0.092447065, 0.0913512, -0.014383561, 0.063214146, 0.053727426, -0.052776184, 0.0124870185, 0.035161685], 
[0.08690599, 0.05784749, -0.04990616, 0.046923604, -0.09493818, 0.039592326, -0.0681406, -0.0100583015, 0.002527988, 0.050478518], 
[-0.038304657, -0.04051114, 0.032434523, 0.089703165, -0.107846774, 0.051171232, 0.1008754, 0.01855718, 0.03945135, 0.093939185], 
[-0.09491692, -0.09137712, 0.06404795, 0.067243814, -0.0106779635, 0.04851935, -0.017268598, 0.08663416, -0.080681026, -0.018173749], 
[0.02763257, -0.09830963, 0.03175527, -0.0501899, 0.025570465, 0.06714851, 0.10583758, 0.022618258, 0.09970327, -0.03760578], 
[0.05389991, -0.0007294059, -0.038267154, 0.051177766, 0.027830018, -0.049324866, -0.09397058, 0.019444704, 0.038120378, 0.1018271], 
[-0.06049036, -0.08021841, 0.008310283, 0.015323318, -0.04247849, -0.035448324, -0.06655277, -0.055549145, -0.08485063, -0.068060115], 
[0.00067220925, -0.04423622, -0.07314588, 0.016712893, 0.040692758, 0.10371292, -0.10161414, 0.058253873, 0.06384116, 0.07742293], 
[0.048071492, 0.106393576, -0.08205235, 0.088580586, 0.016896164, 0.0008048654, 0.017253816, 0.07914151, -0.07914438, -0.03801256]])
after: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
after: array([[-0.053856265, -0.012414492, -0.03389482, -0.032783605, -0.036595266, ..., 0.021453798, -0.08761745, 0.018842554, -0.029692769, 0.07753774], 
[-0.042544525, -0.07293815, 0.06097107, 0.0416492, -0.03790271, ..., 0.06082928, 0.08777118, -0.08429338, -0.08076069, -0.06771054], 
[-0.08845841, 0.029448688, 0.06328565, -0.03410713, -0.036064595, ..., 0.027307177, -0.021130813, -0.035200007, -0.057193916, -0.041510485], 
[-0.018982172, 0.08534098, -0.056084108, -0.03576771, 0.017816579, ..., -0.011001724, 0.036977615, 0.004757029, -0.0012149811, -0.08328989], 
[0.069201194, 0.012863481, -0.04930165, 0.057904374, -0.03371034, ..., 0.079692, 0.07050877, -0.025478942, 0.04071628, 0.07549286], 
[-0.02366817, -0.034837246, 0.066772535, -0.031363845, 0.08390447, ..., 0.047260202, 0.000983286, -0.03632293, -0.020872552, 0.0270023], 
[-0.065769196, -0.024373615, -0.046084378, -0.044837113, 0.05775031, ..., 0.012314904, 0.049477816, 0.000722611, 0.07396825, -0.028268421], 
[0.049253847, -0.033319242, -0.02716217, -0.0229196, -0.08651853, ..., -0.054741055, -0.023097748, -0.04210357, -0.072810926, -0.040404987], 
[-0.027974779, -0.064854, 0.010344154, -0.07395566, -0.041873347, ..., -0.020380521, -0.059522163, -0.028937632, 0.034034397, -0.08065272], 
[-0.054513197, 0.032668687, 0.034424316, 0.085339785, 0.0830488, ..., -0.008547771, 0.05197618, -0.07809673, 0.049727358, 0.03880323]])
after: array([0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0])
```

2023-04-20 05:00 UTC, AsakusaRinne requested changes

2023-04-20 05:00 UTC, AsakusaRinne commented on src/TensorFlowNET.Keras/Engine/Layer.cs
> +                if (weights[i].shape != Weights[i].shape)
The condition seems to be too strict. For example, shape A is (-1, 10), shape B is (8, 10) is also compatible. (refer to function `is_compatible_with` in tensorflow).

2023-04-20 05:27 UTC, Wanglongzhi2001 commented on src/TensorFlowNET.Keras/Engine/Layer.cs
> +        public virtual void set_weights(List<NDArray> weights)
Thank you for your valuable advice, I will revise it. ^_^

2023-04-21 09:24 UTC, AsakusaRinne approved these changes

2023-04-21 11:37 UTC, Oceania2018 approved these changes

2023-04-21 11:37 UTC, merged